;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname 1-10-18) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(require picturing-programs)
(define (on-parabola posn)
  (make-posn (posn-x posn)
             (sqr (posn-x posn))))
(define (draw-h posn)
  (place-image (circle 3 "solid" "blue")
               (posn-x posn)
               (posn-y posn)
               (empty-scene 200 200)))
(define (tick-h posn)
  (make-posn (+ (posn-x posn)
                1)
             (posn-y posn)))
(big-bang (make-posn 0 0)
          (on-tick tick-h 1)
          (on-draw draw-h))
(define (mix-color color)
  (make-color (* 2 (color-green color))
              (round (* .5 (color-red color)))
              (round (/ (+ (color-red color)
                           (color-green color)
                           (color-blue color))
                        3))))
