;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname posn-util) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(require picturing-programs)
(provide (all-defined-out))
(define (swap-x-y posn)
  (make-posn (posn-y posn)
             (posn-x posn)))
(define (scale-posn posn scale)
  (make-posn (* (posn-x posn)
                scale)
             (* (posn-y posn)
                scale)))
(define (add-posns posn1 posn2)
  (make-posn (+ (posn-x posn1)
                (posn-x posn2))
             (+ (posn-y posn1)
                (posn-y posn2))))
(define (sub-posn posn1 posn2)
  (make-posn (- (posn-x posn1)
                (posn-x posn2))
             (- (posn-y posn1)
                (posn-y posn2))))
(define (choose-posn dir posn1 posn2)
  (cond [(string=? dir "first") (make-posn (posn-x posn1)
                                           (posn-y posn1))]
        [(string=? dir "second") (make-posn (posn-x posn2)
                                            (posn-y posn2))]
        [else (error "This is not a valid string (Not 'first' or 'second')")]))