(require picturing-programs)
(define-struct si (ex ey tx bulx buly bomx bomy edir))
;GAME ELEMENTS
(define BACKGROUND (empty-scene 500 500))
(define BULLET (rectangle 2 30 "solid" "blue"))
(define TURRET (above (rectangle 6 2 "solid" "black")
                      (rectangle 50 20 "solid" "green")))
(define ENEMY (ellipse 50 20 "solid" "red"))
(define BOMB (circle 5 "solid" "red"))
(define START (make-si 100 10 25 -100 -100 -100 -100 1))
;LOGIC
(define (bullet-hit-enemy? si)
  (and (< (+ -25 (si-ex si))
          (si-bulx si))
       (> (+ 25 (si-ex si))
          (si-bulx si))
       (>= (si-ey si)
           (+ 15 (si-buly si)))))
(define (enemy-hit-turret? si)
  (and (< 15 (si-ey si))
       (or (< (+ -25 (si-ey si))
              (+ 25 (si-tx si)))
           (< (+ 25 (si-ey si))
              (+ -25 (si-tx si))))))
(define (bomb-hit-turret? si)
  (and (< (+ -25 (si-tx si))
          (si-bomx si))
       (> (+ 25 (si-tx si))
          (si-bomx si))
       (>= 10 (si-bomy si))))
(define (bullet-on-screen? si)
  (< -25 (si-buly si)))
(define (game-over? si)
  (or (enemy-hit-turret? si)
      (bomb-hit-turret? si)
      (bullet-hit-enemy? si)))
(define (enemy-left? si)
  (> 50 (si-ex si)))
(define (enemy-right? si)
  (< 450 (si-ex si)))
;DRAW
(define (draw si)
  (place-image BOMB (si-bomx si)
               (si-bomy si)
               (place-image BULLET (si-bulx si)
                            (si-buly si)                
                            (place-image TURRET (si-tx si)
                                         490
                                         (place-image ENEMY (si-ex si)
                                                      (si-ey si)
                                                      BACKGROUND)))))
;TICK
(define (bomb-tick si)
  (make-si (si-ex si)
           (si-ey si)
           (si-tx si)
           (si-bulx si)
           (si-buly si)
           (si-bomx si)
           (+ 50 (si-bomy si))
           (si-edir si)))
(define (bullet-tick si)
  (make-si (si-ex si)
           (si-ey si)
           (si-tx si)
           (si-bulx si)
           (+ -10 (si-buly si))
           (si-bomx si)
           (si-bomy si)
           (si-edir si)))
(define (enemy-tick si)
  (make-si (cond [(= (si-edir si) 1)
                  (+ 50 (si-ex si))]
                 [(= (si-edir si) -1)
                  (+ -50 (si-ex si))]
                 [else (error "What the actual fuck how did you break this")])
           (cond [(or (enemy-left? si) (enemy-right? si))
                  (+ (si-ey si) 10)]
                 [else (si-ey si)])
           (si-tx si)
           (si-bulx si)
           (si-buly si)
           (cond [(< 500 (si-bomy si))
                  (si-bomy
                   (si-ey si))]
                 [else (si-bomy si)])
           (cond [(< 500 (si-bomy si))
                  (si-bomx
                   (si-ex si))]
                 [else (si-bomx si)])
           (cond [(enemy-left? si) 1]
                 [(enemy-right? si) -1]
                 [else (si-edir si)])))
(define (tick si)
  (enemy-tick (bullet-tick (bomb-tick si))))

;BIG-BANG
(big-bang START
          (name "Space Invaders")
          (on-draw draw)
          (on-tick tick .5))
  
